name: Get Feed

on:
  schedule:
    - cron: '30 04 * * *' # 6pm IST
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_API_TOKEN: ntn_ZI930493154370T2BgfftIv4WbZJdEVMe7WdAjkmGWB6Pg
      NOTION_READER_DATABASE_ID: 1d20377632e28171b4b3e55f2e469673
      NOTION_FEEDS_DATABASE_ID: 1d20377632e2815d89bdda24df225826
      RUN_FREQUENCY: 60 # in seconds
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Update Notion Feed
        run: |
          curl -o index.js https://raw.githubusercontent.com/ravgeetdhillon/notion-feeder/build/dist/index.js
          node index.js
